name: Cypress Tests

on: 
    push:
        branches:
            - master
        paths:
            - 'cypress/**'
            - '.github/workflows/cypress-project.yml'

jobs:
  cypress-project-tests:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 20.14.0

        - name: Install dependencies
          run: npm install

        - name: Run Cypress tests (headless)
          run: npx cypress run