name: Cypress Tests

on:
  push:
    branches:
      - master
    paths:
      - 'cypress-project/**'  # observa tudo dentro da pasta
      - '.github/workflows/**'  # caso altere o workflow também

jobs:
  cypress-project-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.14.0

      - name: Install dependencies
        run: npm ci
        working-directory: ./cypress-project

      - name: Run Cypress tests (headless)
        run: npx cypress run
        working-directory: ./cypress-project
